CHAINS = {
    "alvey": "alvey",
    "aptos": "aptos",
    "arbitrum": "arbitrum",
    "arbitrumnova": "arbitrumnova",
    "astar": "astar",
    "aurora": "aurora",
    "avalanche": "avalanche",
    "avax dfk": "dfk",
    "bnb chain": "bsc",
    "base": "base",
    "bitgert": "bitgert",
    "bitrock": "bitrock",
    "boba": "boba",
    "canto": "canto",
    "celo": "celo",
    "conflux": "conflux",
    "core dao": "coredao",
    "cronos": "cronos",
    "cube": "cube",
    "dogechain": "dogechain",
    "echelon": "echelon",
    "elastos": "elastos",
    "energi": "energi",
    "etc": "etc",
    "ethereum": "ether",
    "ethereum goerli": "ethergoerli",
    "ethf": "ethf",
    "ethw": "ethw",
    "evmos": "evmos",
    "exosama": "exosama",
    "fantom": "fantom",
    "filecoin": "filecoin",
    "flare": "flare",
    "fuse": "fuse",
    "fusion": "fusion",
    "gnosis": "gnosis",
    "harmony": "harmony",
    "heco": "heco",
    "hoo": "hoo",
    "iotex": "iotex",
    "kcc": "kucoin",
    "kardia": "kardia",
    "kava": "kava",
    "kek": "kek",
    "klaytn": "klaytn",
    "linea": "linea",
    "mantle": "mantle",
    "meter": "meter",
    "metis": "metis",
    "milkomeda": "milkomeda",
    "moonbeam": "moonbeam",
    "moonriver": "moonriver",
    "muu": "muu",
    "nova network": "nova",
    "okc": "oec",
    "oasis": "oasis",
    "opbnb": "opbnb",
    "optimism": "optimism",
    "polygon": "polygon",
    "polygon zkevm": "polygonzkevm",
    "proof of memes": "pom",
    "pulsechain": "pulse",
    "redlight": "redlight",
    "ronin": "ronin",
    "rsk": "rsk",
    "shib": "shib",
    "shibarium": "shibarium",
    "shibarum": "shibarium",
    "shiden": "shiden",
    "smartbch": "smartbch",
    "solana": "solana",
    "starknet": "starknet",
    "sx": "sx",
    "syscoin": "syscoin",
    "telos": "telos",
    "thundercore": "thundercore",
    "tomb": "tomb",
    "tomo": "tomo",
    "ultron": "ultron",
    "velas": "velas",
    "wan": "wan",
    "zksync": "zksync",
    "elrond": "elrond",
}